### ISSUE TITLE
Installation guide mislead

### ISSUE THREAD

**Issue by nickosh** [fboender/jerrybuild#6]
> If Pip (the Python package manager) is available on your system, you can install Jerrybuild using Pip:

No packet in pip

> Get the latest .deb package for your distribution from the Releases page

Empty Releases page

**Comment by fboender** [comment]
Hey Nickosh!

This repository used to be private, until a long time ago a friend asked if I could make it public. I slapped some documentation on it from a different project and sent it on its merry way. So you've kind of landed in some rough territory here. I'm still using Jerrybuild myself and it's been working for me so far. If you're still interested in using it, I'll do my best to update the documentation and fix any bugs you may encounter.

As for this one, I'm thinking about creating a single stand-alone binary as a distribution mechanism (much like Go programs are distributed). In the meantime, you can try running it direct from a clone of the git repo.

I'll keep you updated.

**Comment by nickosh** [comment]
Hi Fboender! Thanks for your quick response. About documentation - its ok. I really like yours ideas into Jerrybuild and want to try it myself. I'm just looking for a small easy build server with similar functionality and your project looks very suitable. Right now I want to try it on my server but stuck with installation. I write some info in other issue.

**Comment by fboender** [comment]
It's been over a year, but I've completely revamped the basic project structure of Jerrybuild and have released an initial alpha version (v1.0.0-alpha). It's available from the [Releases](https://github.com/fboender/jerrybuild/releases/) page and in PyPi (pip) as package "jerrybuild". You can find installation instructions and more documentation at [readthedocs](https://jerrybuild.readthedocs.io/en/latest/).
