### ISSUE TITLE
Install from Git repo issue on CentOS7

### ISSUE THREAD

**Issue by nickosh** [fboender/jerrybuild#7]
> adduser --system --disabled-password --home /var/lib/jerrybuild \
>         --shell /bin/sh --no-create-home --quiet --force-badname \
>         --group jerrybuild

There no **disabled-password**, **quiet**, **force-badname** and **group** keys for adduser on CentOS7.

**Comment by fboender** [comment]
Installation instructions have been updated to work on CentOS7. You can find installation instructions and more documentation at [readthedocs](https://jerrybuild.readthedocs.io/en/latest/).
